### ISSUE TITLE
Is there a roadmap for FreeSurfer.jl?

### ISSUE THREAD

**Issue by bhvieira** [lincbrain/Fibers.jl#14]
Congratulations on this fantastic idea! I was really hoping something for Freesurfer in Julia was going on.

Is there a roadmap? Should Freesurfer.jl implement the recon-all streams as well? I would definitely like to help with that :)

**Comment by ayendiki** [comment]
Hi! It started as a bit of a pet project, so it's been focused on dMRI so far, but the sky is the limit! Would love to hear what others would be interested in implementing. Any chance you'll be at OHBM?

**Comment by bhvieira** [comment]
I'll be there, yes! Establishing a roadmap could be a nice project for one of the Brainhacks as well

**Comment by ayendiki** [comment]
I'd definitely be up for doing a julia project at Brainhack if there's interest!

**Comment by bhvieira** [comment]
I'm on the OHBM BrainHack organizing team this year, so I don't know if I can commit this time, but I'm definitely interested.

**Comment by ayendiki** [comment]
No worries, it can be December. But it'd be good to poll people for interest at OHBM brainhack so we can have at least some discussion ahead of time.

**Comment by bhvieira** [comment]
This might be interesting for a prospect of porting the recon-all routines to Julia:

[https://surfer.nmr.mgh.harvard.edu/fswiki/ReconAllFilesVsSteps](https://surfer.nmr.mgh.harvard.edu/fswiki/ReconAllFilesVsSteps)

![image](https://github.com/freesurfer/FreeSurfer.jl/assets/18633953/e31cc071-29c1-489c-8206-66001f986ede)
